# Generated by Django 5.1.2 on 2025-02-26 23:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="user_id",
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="email address"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="matches",
            field=models.ManyToManyField(
                blank=True, related_name="matched_by", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="swiped_users",
            field=models.ManyToManyField(
                blank=True, related_name="swiped_by", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
