# Generated by Django 5.1.7 on 2025-04-11 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vote_weight',
            field=models.IntegerField(default=1),
        ),
    ]
