# Generated by Django 5.1.7 on 2025-04-12 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_vote_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='height',
        ),
    ]
