# Generated by Django 5.1.7 on 2025-04-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('trusted', 'Trusted'), ('moderator', 'Moderator'), ('admin', 'Admin')], default='regular', max_length=20),
        ),
    ]
