# Generated by Django 5.1.7 on 2025-04-16 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sexual_preference',
            field=models.CharField(blank=True, choices=[('straight', 'Straight'), ('gay', 'Gay'), ('bisexual', 'Bisexual'), ('asexual', 'Asexual'), ('pansexual', 'Pansexual'), ('other', 'Other')], max_length=20, null=True),
        ),
    ]
