# Generated by Django 5.1.7 on 2025-04-24 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_user_profile_pictures_profilepicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.DeleteModel(
            name='ProfilePicture',
        ),
    ]
