# Generated by Django 5.1.7 on 2025-04-24 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_profilepicture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
    ]
