# Generated by Django 5.1.7 on 2025-04-20 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_alter_groupchat_options_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupchat',
            options={},
        ),
    ]
