# Generated by Django 5.1.7 on 2025-04-21 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0006_alter_groupchat_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupchat',
            options={'ordering': ['-created_at']},
        ),
    ]
