# Generated by Django 5.1.7 on 2025-04-21 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0007_alter_groupchat_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupchat',
            options={},
        ),
    ]
