# Generated by Django 5.1.7 on 2025-04-11 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_eventattendee_event_alter_eventattendee_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventAttendee',
        ),
    ]
