# Generated by Django 5.1.7 on 2025-04-18 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_delete_eventattendee'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='day_of_week',
            field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], default='monday', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='tag_color',
            field=models.CharField(choices=[('red', 'Deal/Special'), ('blue', 'Event')], default='red', max_length=10),
            preserve_default=False,
        ),
    ]
