# Generated by Django 5.1.7 on 2025-04-18 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_day_of_week_event_tag_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='tag_color',
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('RED', 'Deal / Drink Special'), ('BLUE', 'Event')], default='Monday', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='day_of_week',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10),
        ),
    ]
