# Generated by Django 5.1.7 on 2025-04-12 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_alter_match_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['-created_at']},
        ),
    ]
