# Generated by Django 5.1.7 on 2025-03-14 20:56

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('music_genre', models.CharField(choices=[('rock', 'Rock'), ('jazz', 'Jazz'), ('pop', 'Pop'), ('hip-hop', 'Hip-Hop'), ('electronic', 'Electronic'), ('other', 'Other')], default='other', max_length=100)),
                ('average_price', models.CharField(max_length=50)),
                ('event', models.CharField(blank=True, max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='BarRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('review', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BarStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crowd_size', models.CharField(choices=[('empty', 'Empty'), ('low', 'Low'), ('moderate', 'Moderate'), ('busy', 'Busy'), ('crowded', 'Crowded'), ('packed', 'Packed')], max_length=50)),
                ('wait_time', models.CharField(choices=[('<5 min', 'Less than 5 minutes'), ('5-10 min', '5 to 10 minutes'), ('10-20 min', '10 to 20 minutes'), ('20-30 min', '20 to 30 minutes'), ('>30 min', 'More than 30 minutes')], max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
