# Generated by Django 5.1.2 on 2025-02-26 22:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bar_id", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("music_genre", models.CharField(max_length=100)),
                ("average_price", models.CharField(max_length=50)),
                ("event", models.CharField(blank=True, max_length=100)),
                ("location", models.CharField(max_length=255)),
                (
                    "current_crowd",
                    models.CharField(
                        choices=[
                            ("empty", "Empty"),
                            ("low", "Low"),
                            ("moderate", "Moderate"),
                            ("busy", "Busy"),
                            ("crowded", "Crowded"),
                        ],
                        max_length=50,
                    ),
                ),
                ("current_wait_time", models.CharField(max_length=50)),
                (
                    "users_at_bar",
                    models.ManyToManyField(
                        blank=True,
                        related_name="bars_visited",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
