# Generated by Django 5.1.7 on 2025-03-14 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bars', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='users_at_bar',
            field=models.ManyToManyField(blank=True, related_name='bars_visited', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='barrating',
            name='bar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='bars.bar'),
        ),
        migrations.AddField(
            model_name='barrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bar_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='barstatus',
            name='bar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to='bars.bar'),
        ),
        migrations.AddIndex(
            model_name='bar',
            index=models.Index(fields=['name'], name='bars_bar_name_609295_idx'),
        ),
        migrations.AddIndex(
            model_name='barrating',
            index=models.Index(fields=['rating'], name='bars_barrat_rating_f205c4_idx'),
        ),
        migrations.AddIndex(
            model_name='barrating',
            index=models.Index(fields=['timestamp'], name='bars_barrat_timesta_bf683b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='barrating',
            unique_together={('bar', 'user')},
        ),
    ]
