# Generated by Django 5.1.2 on 2025-02-28 23:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bars", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="bar",
            name="users_at_bar",
            field=models.ManyToManyField(
                blank=True, related_name="bars_visited", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="barstatus",
            name="bar",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_updates",
                to="bars.bar",
            ),
        ),
    ]
