# Generated by Django 5.1.2 on 2025-02-26 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bars", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bar",
            name="bar_id",
        ),
        migrations.CreateModel(
            name="BarStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "crowd_size",
                    models.CharField(
                        choices=[
                            ("empty", "Empty"),
                            ("low", "Low"),
                            ("moderate", "Moderate"),
                            ("busy", "Busy"),
                            ("crowded", "Crowded"),
                        ],
                        max_length=50,
                    ),
                ),
                ("wait_time", models.CharField(max_length=50)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "bar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_updates",
                        to="bars.bar",
                    ),
                ),
            ],
        ),
    ]
