# Generated by Django 5.1.7 on 2025-03-15 05:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar',
            name='users_at_bar',
            field=models.ManyToManyField(blank=True, related_name='bars_attended', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='bar',
            index=models.Index(fields=['location'], name='bars_bar_locatio_0cb051_idx'),
        ),
    ]
