# Generated by Django 5.1.7 on 2025-03-08 08:41

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bars", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BarRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.PositiveSmallIntegerField()),
                ("review", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="bar",
            name="current_crowd",
            field=models.CharField(
                choices=[
                    ("empty", "Empty"),
                    ("low", "Low"),
                    ("moderate", "Moderate"),
                    ("busy", "Busy"),
                    ("crowded", "Crowded"),
                    ("packed", "Packed"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="bar",
            name="current_wait_time",
            field=models.CharField(
                choices=[
                    ("<5 min", "Less than 5 minutes"),
                    ("5-10 min", "5 to 10 minutes"),
                    ("10-20 min", "10 to 20 minutes"),
                    ("20-30 min", "20 to 30 minutes"),
                    (">30 min", "More than 30 minutes"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="bar",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                geography=True, srid=4326
            ),
        ),
        migrations.AlterField(
            model_name="barstatus",
            name="crowd_size",
            field=models.CharField(
                choices=[
                    ("empty", "Empty"),
                    ("low", "Low"),
                    ("moderate", "Moderate"),
                    ("busy", "Busy"),
                    ("crowded", "Crowded"),
                    ("packed", "Packed"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="barstatus",
            name="wait_time",
            field=models.CharField(
                choices=[
                    ("<5 min", "Less than 5 minutes"),
                    ("5-10 min", "5 to 10 minutes"),
                    ("10-20 min", "10 to 20 minutes"),
                    ("20-30 min", "20 to 30 minutes"),
                    (">30 min", "More than 30 minutes"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="bar",
            index=models.Index(fields=["name"], name="bars_bar_name_609295_idx"),
        ),
        migrations.AddIndex(
            model_name="bar",
            index=models.Index(
                fields=["current_crowd"], name="bars_bar_current_6dd2ea_idx"
            ),
        ),
        migrations.AddField(
            model_name="barrating",
            name="bar",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings",
                to="bars.bar",
            ),
        ),
        migrations.AddField(
            model_name="barrating",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bar_ratings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="barrating",
            index=models.Index(fields=["rating"], name="bars_barrat_rating_f205c4_idx"),
        ),
        migrations.AddIndex(
            model_name="barrating",
            index=models.Index(
                fields=["timestamp"], name="bars_barrat_timesta_bf683b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="barrating",
            unique_together={("bar", "user")},
        ),
    ]
