# Generated by Django 5.1.7 on 2025-04-09 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0004_remove_bar_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bar',
            name='music_genre',
        ),
    ]
