# Generated by Django 5.1.7 on 2025-04-13 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0005_remove_bar_music_genre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BarVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crowd_size', models.CharField(choices=[('empty', 'Empty'), ('low', 'Low'), ('moderate', 'Moderate'), ('busy', 'Busy'), ('crowded', 'Crowded'), ('packed', 'Packed')], max_length=50)),
                ('wait_time', models.CharField(choices=[('<5 min', 'Less than 5 minutes'), ('5-10 min', '5 to 10 minutes'), ('10-20 min', '10 to 20 minutes'), ('20-30 min', '20 to 30 minutes'), ('>30 min', 'More than 30 minutes')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='bars.bar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bar_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['bar'], name='bars_barvot_bar_id_4bad8d_idx'), models.Index(fields=['user'], name='bars_barvot_user_id_aa6f50_idx'), models.Index(fields=['timestamp'], name='bars_barvot_timesta_5b2ba9_idx')],
                'unique_together': {('bar', 'user')},
            },
        ),
    ]
