# Generated by Django 5.1.7 on 2025-04-14 20:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0006_barvote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='barvote',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='barvote',
            constraint=models.UniqueConstraint(fields=('bar', 'user'), name='unique_vote_per_bar_user'),
        ),
    ]
