# Generated by Django 5.1.7 on 2025-04-18 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0007_alter_barvote_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='bar_images/%Y/%m/%d/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bars.bar')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
