# Generated by Django 5.1.7 on 2025-04-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0008_barimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barimage',
            name='image',
        ),
        migrations.AddField(
            model_name='barimage',
            name='image_url',
            field=models.URLField(default='https://cdn.vox-cdn.com/thumbor/Vf3h_21tEyorqjgI6JKsCAuVEGs=/0x0:1800x1349/1820x1213/filters:focal(956x435:1244x723):format(webp)/cdn.vox-cdn.com/uploads/chorus_image/image/58879909/Web_05.0.jpg', max_length=500),
            preserve_default=False,
        ),
    ]
