# Generated by Django 5.1.7 on 2025-04-21 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0009_remove_barimage_image_barimage_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='barimage',
            name='image',
            field=models.ImageField(default='https://s3-media0.fl.yelpcdn.com/bphoto/8jLuecWKcUqIEUKjs0TRcA/348s.jpg', upload_to='bar_images/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
