# Generated by Django 5.1.7 on 2025-04-21 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0010_remove_barimage_image_url_barimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barimage',
            name='image',
            field=models.URLField(max_length=500),
        ),
    ]
