# Generated by Django 5.1.7 on 2025-04-25 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0011_alter_barimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10)),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='bars.bar')),
            ],
            options={
                'ordering': ['day'],
                'indexes': [models.Index(fields=['bar'], name='bars_barhou_bar_id_503544_idx'), models.Index(fields=['day'], name='bars_barhou_day_018e89_idx')],
                'unique_together': {('bar', 'day')},
            },
        ),
    ]
