# Generated by Django 5.1.7 on 2025-06-20 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0014_convert_barstatus_to_onetoone'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='active_user_count',
            field=models.IntegerField(default=0),
        ),
    ]
