# Generated by Django 5.1.7 on 2025-06-20 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0015_bar_active_user_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bar',
            name='active_user_count',
        ),
    ]
