# Generated by Django 5.1.7 on 2025-06-22 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0016_remove_bar_active_user_count'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='barcrowdsize',
            name='unique_crowd_size_vote_per_bar_user',
        ),
        migrations.RemoveConstraint(
            model_name='barvote',
            name='unique_wait_time_vote_per_bar_user',
        ),
    ]
