name: BarBuddy iOS Build and Test

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'backend/**'
      - 'frontend/**'
      - '.gitignore'
      - 'docs/**'
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build-and-test:
    name: iOS Build and Test
    runs-on: macos-15
    timeout-minutes: 25
    strategy:
      matrix:
        ios-version: ['17.2', '18.0']
      fail-fast: false
      max-parallel: 2

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.3'

      - name: Verify Xcode Version
        run: xcodebuild -version

      # Optimized cache for SPM only
      - name: Cache Swift Package Manager
        uses: actions/cache@v4
        with:
          path: |
            ~/Library/Caches/org.swift.swiftpm
            ~/Library/Developer/Xcode/DerivedData/**/SourcePackages
            .build
            **/SourcePackages
          key: ${{ runner.os }}-spm-${{ matrix.ios-version }}-${{ hashFiles('**/Package.resolved', '**/Package.swift') }}
          restore-keys: |
            ${{ runner.os }}-spm-${{ matrix.ios-version }}-
            ${{ runner.os }}-spm-

      # Lightweight DerivedData cache (excluding SourcePackages to avoid conflicts)
      - name: Cache Build Data
        uses: actions/cache@v4
        with:
          path: |
            DerivedData/Build/Intermediates.noindex
            DerivedData/Build/Products
            DerivedData/ModuleCache.noindex
          key: ${{ runner.os }}-build-${{ matrix.ios-version }}-${{ hashFiles('**/Package.resolved', '**/*.xcodeproj/project.pbxproj') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ matrix.ios-version }}-
            ${{ runner.os }}-build-

      # Cache iOS Simulator Runtimes
      - name: Cache iOS Simulator Runtimes
        uses: actions/cache@v4
        with:
          path: |
            ~/Library/Caches/com.apple.dt.Xcode/Downloads
            ~/Library/Developer/CoreSimulator/Profiles/Runtimes
          key: ${{ runner.os }}-simulator-${{ matrix.ios-version }}-xcode-16.3
          restore-keys: |
            ${{ runner.os }}-simulator-${{ matrix.ios-version }}-
            ${{ runner.os }}-simulator-

      - name: Determine Build Configuration
        id: config
        run: |
          # Find project/workspace file
          if [ -n "$(find . -name "*.xcworkspace")" ]; then
            file_to_build=$(find . -name "*.xcworkspace" | head -1)
            filetype_parameter="workspace"
          elif [ -n "$(find . -name "*.xcodeproj")" ]; then
            file_to_build=$(find . -name "*.xcodeproj" | head -1)
            filetype_parameter="project"
          else
            echo "Error: No .xcworkspace or .xcodeproj found"
            exit 1
          fi

          # Get scheme
          scheme_list=$(xcodebuild -list -${filetype_parameter} "${file_to_build}")
          echo "Available schemes:"
          echo "$scheme_list"

          default_scheme=$(echo "$scheme_list" | awk '/Schemes:/,0' | tail -n +2 | head -1 | xargs)
          if [ -z "$default_scheme" ]; then
            echo "Error: Could not determine default scheme"
            exit 1
          fi

          # Find iPhone 16 simulator specifically
          device=$(xcrun simctl list devices available | grep -E "iPhone 16" | head -1 | sed -E 's/^[[:space:]]*([^(]+).*/\1/' | xargs)
          if [ -z "$device" ]; then
            echo "No iPhone 16 simulators found. Available devices:"
            xcrun simctl list devices available | grep iPhone
            exit 1
          fi

          echo "file_to_build=${file_to_build}" >> $GITHUB_OUTPUT
          echo "filetype_parameter=${filetype_parameter}" >> $GITHUB_OUTPUT
          echo "scheme=${default_scheme}" >> $GITHUB_OUTPUT
          echo "device=${device}" >> $GITHUB_OUTPUT

          echo "Configuration:"
          echo "  File: ${file_to_build}"
          echo "  Type: ${filetype_parameter}"
          echo "  Scheme: ${default_scheme}"
          echo "  Device: ${device}"

      # Install iOS runtime if needed
      - name: Install iOS Runtime
        run: |
          REQUIRED_IOS_VERSION="${{ matrix.ios-version }}"
          echo "Checking for iOS $REQUIRED_IOS_VERSION runtime..."
          
          if xcrun simctl list runtimes | grep -q "iOS $REQUIRED_IOS_VERSION"; then
            echo "✓ iOS $REQUIRED_IOS_VERSION runtime available"
          else
            echo "Installing iOS $REQUIRED_IOS_VERSION runtime..."
            xcrun simctl runtime install "iOS $REQUIRED_IOS_VERSION" || {
              echo "⚠️  Could not install iOS $REQUIRED_IOS_VERSION, using available runtime"
            }
          fi

      # Resolve SPM dependencies
      - name: Resolve Swift Package Dependencies
        run: |
          echo "Resolving Swift Package Manager dependencies..."
          
          # Clear cache if commit message contains flag
          if echo "${{ github.event.head_commit.message || '' }}" | grep -q '\[clear-spm-cache\]'; then
            echo "Clearing SPM cache due to commit message flag"
            rm -rf ~/Library/Caches/org.swift.swiftpm
            rm -rf .build
            rm -rf **/SourcePackages
          fi
          
          # Resolve dependencies
          xcodebuild -resolvePackageDependencies \
            -scheme "${{ steps.config.outputs.scheme }}" \
            -${{ steps.config.outputs.filetype_parameter }} "${{ steps.config.outputs.file_to_build }}" \
            -derivedDataPath DerivedData || {
              echo "Failed to resolve dependencies, clearing cache and retrying..."
              rm -rf ~/Library/Caches/org.swift.swiftpm
              rm -rf DerivedData/**/SourcePackages
              xcodebuild -resolvePackageDependencies \
                -scheme "${{ steps.config.outputs.scheme }}" \
                -${{ steps.config.outputs.filetype_parameter }} "${{ steps.config.outputs.file_to_build }}" \
                -derivedDataPath DerivedData
            }

      - name: Prepare iPhone 16 Simulator
        id: simulator
        run: |
          echo "Preparing iPhone 16 simulator: ${{ steps.config.outputs.device }}"

          # Find iPhone 16 simulator UDID
          SIMULATOR_UDID=$(xcrun simctl list devices available | grep "${{ steps.config.outputs.device }}" | head -1 | grep -oE '\([A-F0-9-]+\)' | tr -d '()')

          if [ -z "$SIMULATOR_UDID" ]; then
            echo "Could not find iPhone 16 simulator"
            echo "Available iPhone simulators:"
            xcrun simctl list devices available | grep iPhone
            exit 1
          fi

          echo "Using iPhone 16 simulator: $SIMULATOR_UDID"

          # Boot simulator
          xcrun simctl boot "$SIMULATOR_UDID" || echo "Simulator may already be booted"
          xcrun simctl bootstatus "$SIMULATOR_UDID" -b

          echo "simulator_udid=${SIMULATOR_UDID}" >> $GITHUB_OUTPUT

      # Check if tests exist
      - name: Check for Tests
        id: check-tests
        run: |
          if find . -name "*Tests.swift" -o -name "*Test.swift" | grep -q .; then
            echo "has-tests=true" >> $GITHUB_OUTPUT
            echo "✓ Test files found"
          else
            echo "has-tests=false" >> $GITHUB_OUTPUT
            echo "ℹ️  No test files found"
          fi

      - name: Build for Testing
        timeout-minutes: 8
        run: |
          set -o pipefail
          xcodebuild build-for-testing \
            -scheme "${{ steps.config.outputs.scheme }}" \
            -${{ steps.config.outputs.filetype_parameter }} "${{ steps.config.outputs.file_to_build }}" \
            -destination "platform=iOS Simulator,name=${{ steps.config.outputs.device }}" \
            -configuration Debug \
            -derivedDataPath DerivedData \
            CODE_SIGNING_ALLOWED=NO \
            | xcpretty --color --report junit --output build-results.xml || true

      - name: Run Tests
        if: steps.check-tests.outputs.has-tests == 'true'
        timeout-minutes: 8
        run: |
          set -o pipefail
          xcodebuild test-without-building \
            -scheme "${{ steps.config.outputs.scheme }}" \
            -${{ steps.config.outputs.filetype_parameter }} "${{ steps.config.outputs.file_to_build }}" \
            -destination "platform=iOS Simulator,name=${{ steps.config.outputs.device }}" \
            -configuration Debug \
            -derivedDataPath DerivedData \
            -parallel-testing-enabled NO \
            -resultBundlePath TestResults \
            CODE_SIGNING_ALLOWED=NO \
            | xcpretty --color --report junit --output test-results.xml

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-ios-${{ matrix.ios-version }}
          path: |
            test-results.xml
            build-results.xml
            TestResults/
            DerivedData/Logs/
        continue-on-error: true

      # Optional: Upload build artifacts
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: build-logs-ios-${{ matrix.ios-version }}
          path: |
            DerivedData/Logs/
        continue-on-error: true
