name: iOS starter workflow

on:
  push:
    branches: [ "network-call-refactor" ] 
  pull_request:
    branches: [ "network-call-refactor" ]

jobs:
  build:
    name: BarBuddy iOS Build and Test
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'

      - name: Verify Xcode Version
        run: xcodebuild -version

      - name: Set Default Scheme
        run: |
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
          echo $default | cat >default
          echo Using default scheme: $default

      - name: Build
        env:
          scheme: ${{ 'default' }}
          platform: ${{ 'iOS Simulator' }}
        run: |
          device=$(xcrun xctrace list devices 2>&1 \
          | grep -oE 'iPhone [^(]+' \
          | while read -r device_name; do
              os_version=$(xcrun xctrace list devices 2>&1 | grep "$device_name" | sed -E 's/.*\(([^)]+)\).*/\1/' | awk '{print $2}')
              major_version=$(echo $os_version | cut -d '.' -f1)
              if [ "$major_version" -ge 18 ]; then
                echo "$device_name"
                break
              fi
            done)

      - name: Test
        env:
          scheme: ${{ 'default' }}
          platform: ${{ 'iOS Simulator' }}
        run: |
          if [ "$scheme" = "default" ]; then scheme=$(cat default); fi
          file_to_build=$(ls -A | grep -i .xcworkspace || ls -A | grep -i .xcodeproj)
          xcodebuild build-for-testing -scheme "$scheme" -project "$file_to_build" -destination "platform=$platform,name=$device"
